# Generated by Django 3.0.4 on 2021-07-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('nationalite', models.CharField(max_length=100, null=True)),
                ('langueMaternelle', models.CharField(max_length=100, null=True)),
                ('langueParlee', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('exterieur', 'exterieur'), ('interne', 'interne')], max_length=100, null=True)),
                ('date_naissance', models.CharField(max_length=100, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('claSSe', models.CharField(choices=[('Foxes', 'Foxes'), ('Little-Foxes', 'Little-Foxes'), ('Bears', 'Bears'), ('Seals', 'Seals'), ('Owls', 'Owls')], max_length=100, null=True)),
                ('frais_scolarite', models.BooleanField()),
                ('namePere', models.CharField(max_length=100, null=True)),
                ('prenomPere', models.CharField(max_length=100, null=True)),
                ('professionPere', models.CharField(max_length=100, null=True)),
                ('telePere', models.CharField(max_length=100, null=True)),
                ('adressePere', models.CharField(max_length=100, null=True)),
                ('NumCINOuPasseportPere', models.CharField(max_length=100, null=True)),
                ('nameMere', models.CharField(max_length=100, null=True)),
                ('prenomMere', models.CharField(max_length=100, null=True)),
                ('professionMere', models.CharField(max_length=100, null=True)),
                ('teleMere', models.CharField(max_length=100, null=True)),
                ('adresseMere', models.CharField(max_length=100, null=True)),
                ('NumCINOuPasseportMere', models.CharField(max_length=100, null=True)),
                ('nomContactUrgent', models.CharField(max_length=100, null=True)),
                ('lienEnfUrgent', models.CharField(max_length=100, null=True)),
                ('telUrgent', models.CharField(max_length=100, null=True)),
                ('medecinEnf', models.CharField(max_length=100, null=True)),
                ('telMedecinEnf', models.CharField(max_length=100, null=True)),
                ('adresseMedecinEnf', models.CharField(max_length=100, null=True)),
                ('adresseCliniqueEnf', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transport', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('AM-PM', 'AM-PM'), ('NON', 'NON')], max_length=100, null=True)),
                ('enfant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compte.Enfant')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Garde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_garde', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('AM-PM', 'AM-PM'), ('Mercredi PM', 'Mercredi PM'), ('NON', 'NON')], max_length=100, null=True)),
                ('enfant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compte.Enfant')),
            ],
        ),
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_forfait', models.CharField(choices=[('journee-complte', 'journee-complte'), ('demi-journee-matinee', 'demi-journee-matinee'), ('demi-journee-apres-midi', 'demi-journee-apres-midi'), ('2-jours-par-semaine', '2-jours-par-semaine')], max_length=100, null=True)),
                ('enfant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compte.Enfant')),
            ],
        ),
        migrations.CreateModel(
            name='Cantine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cantine', models.CharField(choices=[('4j', '4j'), ('5j', '5j'), ('NON', 'NON')], max_length=100, null=True)),
                ('enfant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compte.Enfant')),
            ],
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assure', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=100, null=True)),
                ('enfant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compte.Enfant')),
            ],
        ),
    ]
